### ISSUE TITLE
Scientific notation

### ISSUE THREAD

**Issue by AnimusXCASH** [astanin/python-tabulate#101]
Hi, 

when decimals such as 0.0000001 is used it returns it in scientific notation despite converting it first to string format through 
number =  0.0000001
stringify = f'{number:.7f}'

**Comment by nrth** [comment]
I ran into a similar issue today (due to `e` being in a string which is actually part of an UUID). This is a bit vague in the documentation, but https://github.com/astanin/python-tabulate#column-alignment 

`disable_numparse` should resolve your issues

**Comment by astanin** [comment]
@AnimusXCASH did the suggested workaround help you?

**Comment by miltondp** [comment]
I ran into the same issue today and I can confirm that adding `disable_numparse=True` solves the problem.

**Comment by chambliss** [comment]
Hi! @astanin sorry to reopen this question, but I was wondering if there's a way to still benefit from intfmt/floatfmt while also disabling scientific notation. Ideally I'd be able to specify that numbers should be displayed with commas but never with scientific notation. Is this possible or not yet?
