### ISSUE TITLE
Tabulate randomly adding trailing decimals to numbers in dataframe

### ISSUE THREAD

**Issue by mikeboiko** [astanin/python-tabulate#106]
I noticed that random decimals are appended to my pandas dataframe values when printing with tabulate. This doesn't happen consistently, which makes it even more strange.

For example, if I perform a regular `print(df)`, I get:

```
                                      2020-12-20    2020-12-19    2020-12-18
usd_cad                                 1.279         1.279         1.276
```

Now if I perform `print(tabulate(df, headers='keys', tablefmt='psql'))`, I get:

```
+---------------------------------+--------------------+--------------------+--------------+
|                                 | 2020-12-20         | 2020-12-19         | 2020-12-18   |
|---------------------------------+--------------------+--------------------+--------------|
| usd_cad                         | 1.2790000000000001 | 1.2790000000000001 | 1.276        |
+---------------------------------+--------------------+--------------------+--------------+
```

The records in the df are of type object.

Just wondering why the extra 000000001 is being added to some values? Notice 1.276 was unchanged though.

Thanks!

**Comment by astanin** [comment]
Unless you share your data, and provide more information about what Python version you use, it's hard to tell what exactly is happening.

1.279 cannot be represented exactly as a floating point number, the number in the data frame is _not_ exaclty 1.279. `print(df)` takes care of hiding rounding errors. Python usually hides last digit errors too, but I don't know what heuristic it now uses.

I suppose something like this is happening:

```
>>> df = pd.DataFrame([[1.279+4.9999999e-16]])
>>> print(df)
       0
0  1.279
>>> print(df[0][0])
1.2790000000000004
```

**Comment by mikeboiko** [comment]
@astanin, I think you're right. I will work on fixing the data in df.
