### ISSUE TITLE
Unicode can mess up alignment even with wcwidth and WIDE_CHARS_MODE on

### ISSUE THREAD

**Issue by DragonRulerX** [astanin/python-tabulate#108]
I've found an issue with representing certain Unicode symbols in tabulate and I'm not sure if this is already known given the other two issues seemingly pointing out a similar issue, but not using emoji's in their claims:
https://github.com/astanin/python-tabulate/issues/52
https://github.com/astanin/python-tabulate/issues/28

I'm pretty new to using GitHub so please excuse the use of pictures instead of the raw data.
I couldn't figure out how to format it so that it wouldn't remove the white space which is the primary point of concern.

Editor Sublime Text3:
Image shows logged table in text file
![image](https://user-images.githubusercontent.com/22264652/105300820-875ea380-5b80-11eb-875d-ddb391226626.png)

Discord:
Image shows code blocked table
![image](https://user-images.githubusercontent.com/22264652/105301532-b248f780-5b80-11eb-869c-ca5fca1d9d5d.png)

PowerShell:
Image shows logged table in PowerShell (just as reference since my terminal is not Unicode aware, but then things line up)
![image](https://user-images.githubusercontent.com/22264652/105302235-ddcbe200-5b80-11eb-89d9-5c8dd005c0bd.png)

This is the raw data:
   usersid | name          | active
-----------+---------------+----------
        26 | ❆ 𝕀𝕧𝕒 🎀 ℕ𝕒 ❆ | True
        34 | 𝓢𝓮𝓽𝓱🌹        | True
        32 | 𝓓𝓪𝓻𝓴 𝓔𝓯𝓯𝓮𝓬𝓽𝔃  | True
         1 | Dragon        | True

**Comment by cmccandless** [comment]
Bump. Can confirm this issue in 0.8.7

**Comment by astanin** [comment]
This issue has been fixed in the current master branch.
See also: pull request #58.

![image](https://user-images.githubusercontent.com/71802/108273854-0ccb7880-716c-11eb-967a-5602c6292d6a.png)

**Comment by DragonRulerX** [comment]
I'm not convinced this was fixed. I just pulled 0.8.9 and tried it and my results were still like my original post. I'm not sure if this is a terminal/editor issue or not, but ultimately Discord still doesn't render it properly, but PowerShell does.

**Comment by joscha** [comment]
I am hitting this issue with the latest version with emojis, specifically 🪦, 👑 and ✅ .

**Comment by Jeiwan** [comment]
To have this fixed you need to install `widechars`:
https://github.com/astanin/python-tabulate#wide-fullwidth-cjk-symbols

**Comment by hoishing** [comment]
I got the same emoji problem, maybe its related to the terminal font also, I use `Sarasa Mono TC` font as a work around
