### ISSUE TITLE
`tabulate.tabulate([['126,000']], tablefmt="html")` raises error starting in 0.8.8

### ISSUE THREAD

**Issue by tomhennigan** [astanin/python-tabulate#110]
Starting in 0.8.8 we're seeing errors when converting to HTML with large numbers encoded as strings:

```python
import tabualate
tabulate.tabulate([['126,000']], tablefmt="html")
```

Error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-37ea0f4d62eb> in <module>()
      1 import tabulate
      2 print(tabulate.__version__)
----> 3 tabulate.tabulate([['126,000']], tablefmt="html")

3 frames
/usr/local/lib/python3.6/dist-packages/tabulate.py in _format(val, valtype, floatfmt, missingval, has_invisible)
   1002             return val.replace(raw_val, formatted_val)
   1003         else:
-> 1004             return format(float(val), floatfmt)
   1005     else:
   1006         return "{0}".format(val)

ValueError: could not convert string to float: '126,000'
```

This works in previous versions of tabulate, see https://colab.research.google.com/gist/tomhennigan/55ffecb257911296cf181ae968a7356a/tabulate-0-8-8-bug.ipynb for an example.

**Comment by evinlort** [comment]
Got the same error with similar string "9,10"
`File "/path_to_virtual_env/lib/python3.7/site-packages/tabulate.py", line 1601, in tabulate
    for c, ct, fl_fmt, miss_v in zip(cols, coltypes, float_formats, missing_vals)`
`File "/path_to_virtual_env/lib/python3.7/site-packages/tabulate.py", line 1601, in 
    for c, ct, fl_fmt, miss_v in zip(cols, coltypes, float_formats, missing_vals)`
`File "/path_to_virtual_env/lib/python3.7/site-packages/tabulate.py", line 1600, in 
    [_format(v, ct, fl_fmt, miss_v, has_invisible) for v in c]`
`File "/path_to_virtual_env/lib/python3.7/site-packages/tabulate.py", line 1004, in _format
    return format(float(val), floatfmt)`
`ValueError: could not convert string to float: '9,10'`

**Comment by ChrisCummins** [comment]
I have also been affected by this when tabulating an integer with commas in it.

**Comment by astanin** [comment]
This is probably related to recent pull request #51.

This exception doesn't happen in Python 2.7:

```
>>> import tabulate as T
>>> T.__version__
u'0.8.9'
>>> print(T.tabulate([["126,000"]], tablefmt="html"))
<table>
<tbody>
<tr><td>126,000</td></tr>
</tbody>
</table>

...

$ echo $LANG
C.UTF-8
$ uname -mo
x86_64 GNU/Linux
$ python --version
Python 2.7.17
```

I can reproduce it in Python 3.

**Comment by astanin** [comment]
For now I added `tabulate([['126,000']])` to the list of regression tests and reverted changes which caused this problem (pr #111).

**Comment by astanin** [comment]
This bug is due to a feature introduced in 0.8.8 (pull request #51).
A regression test was added, and the feature was disabled in 0.8.9 (pull request #111).
It will be implemented differently.
