### ISSUE TITLE
colalign "left" doesn't work for HTML

### ISSUE THREAD

**Issue by swryan** [astanin/python-tabulate#112]
`colalign` "left" doesn't work for HTML...   it results in right alignment as shown below.

I have found that changing 
```
        "left": "",
```
to 
```
        "left": ' style="text-align: left;"',
```
in [tabulate.py:190](https://github.com/astanin/python-tabulate/blob/master/tabulate.py#L190)  fixes the problem.

![image](https://user-images.githubusercontent.com/881430/108549591-5676a900-72bb-11eb-872a-8dc615dbb7ac.png)

**Comment by astanin** [comment]
The idea is that if the user doesn't override default parameters of tabulate, it will produce an HTML without [inline CSS](https://www.bitdegree.org/learn/inline-css). This HTML can be easily embedded elsewhere and restyled. The default alignment in most browsers is _left_.

In your case it appears that Jupyter applies its own stylesheet which overrides the default.

If I accept your suggestion, we'll get to see left alignment in Jupyter, but other users of the `html` output won't be able to get tables without inlines styles, so this can be a _breaking change_ for some other applications.

Current limitation of tabulate is that it doesn't distinguish between "default" behavior when parameter is not specified, and when the parameter is actually specified. I think a better solution would be to have two kinds of HTML generators:

1. Like the current one with inline CSS, which can be directly embedded elsewhere.
2. An unstyled table with some CSS classes, which implies that the user writes her or his own CSS.

As this is a breaking change, I'm reluctant to include in the minor releases. I may suggest to apply a custom Jupyter stylesheet as a workaround. See https://github.com/jiahao/jupyter-stylesheet for inspiration. Alternatively, you can use %%html cell magic:

```
%%html
<style>
// add your CSS styling here
</style>
```

**Comment by swryan** [comment]
perhaps the default should be exactly that, and when you specifically ask for "left", you get left...  currently you ask for left you don't get it...
