### ISSUE TITLE
compact table format

### ISSUE THREAD

**Issue by smjure** [astanin/python-tabulate#116]
First of all thank you for the great module. 

Is there any way to control empty spaces or to make table super compact. I have such case:
![Selection_1011](https://user-images.githubusercontent.com/22912191/109274723-1ca22700-7814-11eb-9292-f69fe7c322bf.png)

I have already shortened variable names as much as possible and the three empty spaces at every column make the table unnecessarily wide. Have tried all `tablefmt`, but no good solution. Is there any workaround? Thanks a lot.

**Comment by magelisk** [comment]
It's not exactly an idea/extensible solution at the moment but you can do the following to get what you want:

``
import tabulate
from tabulate import Line, DataRow, TableFormat

data = [
    [0,0,0,0,0],
    [651,6,7,34,19],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
]
cust_outline = TableFormat(
        lineabove=Line("|", "-", "|", "|"),
        linebelowheader=Line("|", "-", "|", "|"),
        linebetweenrows=None,
        linebelow=None,
        headerrow=DataRow("|", "|", "|"),
        datarow=DataRow("|", "|", "|"),
        padding=0,  # Changed to 0 from 1
        with_header_hide=["lineabove"],
    )

headers=["vCUM", "vAVG", "vSTD", "nb_big", "nb_sml"]
tabulate.MIN_PADDING = 0  # Module level 'patch', not very extensible
result = tabulate.tabulate(data, headers=headers, tablefmt=cust_outline)
print(result)
```


Gives:

![image](https://user-images.githubusercontent.com/18201513/109974473-9bd9a400-7cc7-11eb-8231-b61ffec1ba39.png)

**Comment by dhimmel** [comment]
Would be great to have a compact mode for markdown tables like the one at https://www.tablesgenerator.com/markdown_tables


non compact:

```markdown
| item  | qty |
|-------|-----|
| spam  | 42  |
| eggs  | 451 |
| bacon | 0   |
```

compact:

```markdown
| item | qty |
|---|---|
| spam | 42 |
| eggs | 451 |
| bacon | 0 |
```

In compact mode, each line is written in the most compact way, meaning lines no longer have the same number of characters. This starts to make more sense as the table becomes wide and starts wrapping in text editors.
