### ISSUE TITLE
hope for an parameter to set fixed width of column

### ISSUE THREAD

**Issue by thuzhf** [astanin/python-tabulate#119]
I don't know how to set fixed width for my table, no matter how I change the cell string, it seems it will be always stripped of heading or trailing white spaces. Can you please provide an parameter in tabulate function to set the width of each column in case users want fixed width (set to None if not)?

**Comment by astanin** [comment]
Right now there is a module-level global flag which allows to preserve white space.

```pycon
>>> import tabulate as t
>>> t.PRESERVE_WHITESPACE = True
>>> print(t.tabulate([["foo    "],["a"]], headers="firstrow", tablefmt="grid"))
+-----------+
| foo       |
+===========+
| a         |
+-----------+
```

In the future a similar option might be implemented as named function parameter.

Related: #37 #79
