### ISSUE TITLE
Allow to disable_numparse for specific columns

### ISSUE THREAD

**Issue by letmaik** [astanin/python-tabulate#121]
I have a string column which looks like a number but semantically isn't and which I don't want to reformat. `disable_numparse=True` applies to all columns which is suboptimal since generally the default float formatting is nice. With `disable_numparse=True` the floats end up with a lot of decimals. I propose to extend `disable_numparse` to allow to pass a list of columns not to touch:

```
disable_numparse=["column-a"]
```

Even though not mentioned in the README I saw that `disable_numparse` does actually support specifying individual columns by index, e.g. `[0]`. It would be nice if it would also accept the column name, but this is already good enough I guess.

**Comment by eliegoudout** [comment]
#221 brings this enhancement. With the added `"global"` parameter value for `colalign`, you can tell `tabulate` to not override current alignment. This way, you can have the following:
```pycon
>>> from tabulate import tabulate
>>> print(tabulate(table, colalign=('global', 'center')))
---  ---  ---
  1   2   a
111  222  aaa
---  ---  ---
```
As you can see, column 1 and 3 and "smartly' aligned, but column 2 was aligned on-demand. I invite you to browse through #221 which brings even more flexibility to this behaviour.

One thing to note though: If you had 100 columns, you would still need to generate a long `("global", ..., "global", "center")` if the one column you want center-aligned is far from left.
