### ISSUE TITLE
Improve error reporting when tabular_data is a dict of non-iterable values

### ISSUE THREAD

**Issue by WolfgangFahl** [astanin/python-tabulate#124]
I am trying to tabulate a counter from collections counter
``` python
print(tabulate(counter))
```

this approach gives an error message:
```
 File "/Users/wf/Library/Python/3.8/lib/python/site-packages/tabulate.py", line 1528, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/Users/wf/Library/Python/3.8/lib/python/site-packages/tabulate.py", line 1089, in _normalize_tabular_data
    izip_longest(*tabular_data.values())
TypeError: 'int' object is not iterable
```

**What else should i do - or would this be a feature request?**

**Comment by WolfgangFahl** [comment]
This is what it did so far to get my result - unfortunately floatfmt doesn't seem to work:
```python
def showCounter(self,counter,title,headers=["#","key","count","%"],tablefmt='pretty',limit=50):
        '''
        show the counter contents
        '''
        bins=len(counter.keys())
        limit=min(bins,limit)
        total=sum(counter.values())
        table=[("total",bins,total)]
        for i,bintuple in enumerate(counter.most_common(limit)):
            key,count=bintuple
            table.append((i+1,key,count,count/total*100.0))
        print(title)
        print(tabulate(table,headers=headers,tablefmt=tablefmt,floatfmt=".2f"))
```

**Comment by ivan-radic** [comment]
Hi,

I'd like to second this feature request.
It would be great to have built-in support for `collections` `Counter`s, instead of writing my own wrapper function.

Best regards,
Ivan

**Comment by patrickdeanbrown** [comment]
Hi @WolfgangFahl,

When ```tablefmt='pretty'``` is set, tabulate appears to be treating each column as if it were a string, prior to applying `floatfmt`. So no float formatting is being applied, even though the floatfmt parameter is set. As a workaround, you can either not specify tablefmt, or you can apply the format builtin when calculating your data.

```python
table.append((i + 1, key, count, format(count / total * 100.0, "0.2f")))
```

As for directly using a Counter object with tabulate, you can call the Counter.items() method, and it should work.

```python
from collections import Counter
counter = Counter(['a', 'a', 'a', 'b', 'b', 'c', 'c', 'c', 'c', 'c', 'c', 'c', ])
print(tabulate(counter.items()))

# Expected output:
#
# -  -
# a  3
# b  2
# c  7
# -  -
```

**Comment by WolfgangFahl** [comment]
@patrickdeanbrown  thank you for looking into this. Your workarounds are nice but do not solve the problem/fulfill the need of a simpler interface that this issue is requesting.

**Comment by astanin** [comment]
Tabulate can process an iterable (list) of dictionaries. It should work with a list of `Counter`s too:

```pycon
>>> counter = Counter(a = 3, b = 4)
>>> print(tabulate([dict(c)], headers="keys"))
  a    b
---  ---
  3    4
>>> print(tabulate([c], headers="keys"))
  a    b
---  ---
  3    4
```

**Comment by astanin** [comment]
But the error message can be improved. The library should have suggested what data shape it expects.
