### ISSUE TITLE
Cell Text is Vertical Instead of Horizontal

### ISSUE THREAD

**Issue by twilightsophie** [astanin/python-tabulate#127]
I'm a beginner Python coder so this might be something I'm going wrong but here goes. I'm using Questionary to ask questions of the user, which returns the answers in a dictionary. I then want to present those answers in a table. In testing PrettyTables and this module, I've found that the Tabulate table puts in the answer text vertically with a width of only one character. To demonstrate, here's the output from my terminal, showing the questions, then the answers dictionary, then PrettyTables, then Tabulate. The only instruction I've given is print(tabulate(answers)), as indicated in the documentation.
```? Song Name: Toxic
? Album Name: Singles
? Artist Name Britney Spears
{'song_name_question': 'Toxic', 'album_name_question': 'Singles', 'artist_name_question': 'Britney Spears'}
+-----------+---------+----------------+
| Song Name |  Album  |     Artist     |
+-----------+---------+----------------+
|   Toxic   | Singles | Britney Spears |
+-----------+---------+----------------+
-  -  -
T  S  B
o  i  r
x  n  i
i  g  t
c  l  n
   e  e
   s  y

      S
      p
      e
      a
      r
      s
-  -  -

**Comment by astanin** [comment]
When tabulate is used with a dictionary as data, its values should be iterables of rows (list of rows). A string is an iterable of letters, so every letter becomes a row in your example.
