### ISSUE TITLE
Feature request: Highlight specific rows

### ISSUE THREAD

**Issue by harmony5** [astanin/python-tabulate#128]
Currently, there is no easy way to highlight a specific row if needed, when using tabulate.

For example, let's say I wanted to let the user of a CLI know what was the last entry in a dataset, I could put a symbol at the end of the row (like a * or + sign), or I could color the entire row itself a specific color (I couldn't find a way to showcase it here).

```
 id  name      department  date of entry
---  --------  ----------  -------------
  1  John Doe  IT          2020-06-13
  2  Jane Doe  Marketing   2020-10-21     *
```

Another example would be if different rows needed to be highlighted differently. Let's say, to highlight the rows where there was a positive change with green, and the rows where there was a negative change with red.

```diff
name       symbol  price (US$)     24h high (US$)  24h low (US$)   24h change (%)
---------  ------  --------------  --------------  --------------  --------------
+Akita Inu  AKITA   0.00000145      0.00000149      0.00000127      +12.1
+Shiba Inu  SHIB    0.00000688      0.00000704      0.00000613      +11.8
-Kishu Inu  KISHU   0.000000003025  0.000000003216  0.000000002766  -1.4
```

An example of how this could be used, would be with a function that takes the row as an input, and outputs its formatting. For example, with color:

```python
def highlight(data):
  if data['24h change'] > 0:
    return 'green'
  elif data['24h change'] < 0:
    return 'red'

tabulate(data, headers='keys', highlight=highlight)
```

**Comment by harmony5** [comment]
For the color example, the return could be escape sequence, like *"\e[1;32m"* or *"\e[1;31m"* for example.

**Comment by codysechelski** [comment]
I second this request.

**Comment by gomezschall** [comment]
I second this request, too

**Comment by astanin** [comment]
Highlighting rows does not map well to the tabulate's data model and most of its formats. It is more of a context and usage hing. I suggest to use a post-processing and add color codes later.
