### ISSUE TITLE
New release with maxcolwidths feature

### ISSUE THREAD

**Issue by aantn** [astanin/python-tabulate#131]
Hi,
Would it be possible to get an official release of Tabulate on PyPi which includes the new maxcolwidths feature?

Keep up the great work!

**Comment by aantn** [comment]
To clarify the need for this, I have a Python package which depends on Tabulate and I want to use that feature. I can't just install from git because git dependencies aren't allowed for PyPi packages so that will prevent me from uploading my own package.

**Comment by sabidib** [comment]
Chiming in here as well, would love to have `0.8.10` pushed to PyPI. 

I also have a package I'm publishing that would benefit from this option.

It was surprising the see the feature documented on main, but not pushed to PyPI yet. It seems like the version has been bumped, but not pushed to PyPI. 
 
@astanin I will gladly help move this along!

**Comment by aantn** [comment]
I'm also happy to help out, but does anything need to be done other than pushing the new version to PyPi? I don't have credentials for that, although I could push with an alternative package name if I had to.

**Comment by bmayfi3ld** [comment]
as a workaround you can install it with 
```bash
pip install git+https://github.com/astanin/python-tabulate.git@b2c26bcb70e497f674b38aa7e29de12c0123708a#egg=tabulate
```

**Comment by caffeinism** [comment]
> as a workaround you can install it with
> 
> ```shell
> pip install git+https://github.com/astanin/python-tabulate.git@b2c26bcb70e497f674b38aa7e29de12c0123708a#egg=tabulate
> ```



> To clarify the need for this, I have a Python package which depends on Tabulate and I want to use that feature. I can't just install from git because git dependencies aren't allowed for PyPi packages so that will prevent me from uploading my own package.

**Comment by aantn** [comment]
Any progress on this?

**Comment by siddhpant** [comment]
Seems like no response... Last update to library was 4 months ago with support for 3.10.

Install with `pip install https://github.com/astanin/python-tabulate/archive/master.zip`.

**Comment by vgrabovets** [comment]
This project is used by at least 73.7k public repositories, last release was more than a year ago, this issue is opened almost a year ago, owner still pushes code to the repository within last month. So, is it really so hard to push new version to pypi or provide  explanation why this is not happening?

**Comment by astanin** [comment]
Thank you for the reminder. I've uploaded the latest version as 0.8.10.
