### ISSUE TITLE
Displaying NaN in pandas DataFrames

### ISSUE THREAD

**Issue by rgoubet** [astanin/python-tabulate#133]
Is there a way to specify what should be displayed for NaN values (instead of the string nan), such as an empty string?

**Comment by HavilandTuff** [comment]
It should be possible to use dataFtrame.fillna('') method, but for me in this case tabulate converts all numerical data to strings and instead rounded number like 4.0 I get 4.000000000001 displayed.

**Comment by rgoubet** [comment]
Yes, so eventually, I went to:

`tabulate(df.astype(object).fillna(""))`

**Comment by astanin** [comment]
fillna is probably the best solution. This way tabulate does not have to depend on pandas or use its code directly.
