### ISSUE TITLE
Option to wrap text

### ISSUE THREAD

**Issue by AtomicNess123** [astanin/python-tabulate#134]
Hi! Is it possible to wrap the text in cells of the table when the text is too long? Thanks.

**Comment by bmayfi3ld** [comment]
This looks to be a duplicate of https://github.com/astanin/python-tabulate/issues/90

**Comment by AtomicNess123** [comment]
Yes, thanks. However, that piece of code did not work.

**Comment by bmayfi3ld** [comment]
It has not been released yet, see https://github.com/astanin/python-tabulate/issues/131
