### ISSUE TITLE
Specifying minimum width for the table [Feature Request]

### ISSUE THREAD

**Issue by hash3liZer** [astanin/python-tabulate#136]
I think it would be great if we have a argument to the tabulate which specifies minimum width for the table to be printed. I am asking this because i have a table with 2 columns only and the terminal is on full screen with `1500px` width. While the table only takes about `600px` of the total width. The rest is wasted. 

Maybe, i am lacking the documentation here or some other feature. But if it's not possible with current release. I think it would be great to have one.

**Comment by astanin** [comment]
Most of the output formats are variations of the plain text table formatting. So the width is measured in characters of a monospaced font. Pixel and other CSS widths are only applicable to HTML.

I don't know what is your use case, but the library does not consider output device in any form. The width is adjusted to match the data, not the other way around. You can pad your data with spaces and use `PRESERVE_WHITESPACE` global variable to change library behavior.

Default output:
```pycon
>>> from tabulate import tabulate
>>> print(tabulate([["foo                ", 12]], tablefmt="grid"))
+-----+----+
| foo | 12 |
+-----+----+
```

With `PRESERVE_WHITESPACE`:

```pycon
>>> import tabulate as t
>>> t.PRESERVE_WHITESPACE=True
>>> print(tabulate([["foo                ", 12]], tablefmt="grid"))
+---------------------+----+
| foo                 | 12 |
+---------------------+----+
```

Additionally, you may format you numeric data as strings, pad them with white space and use `disable_numparse` parameter.
Note space around the number "12":

```pycon
>>> print(tabulate([["foo                ", "    12    "]], tablefmt="grid", disable_numparse=True))
+---------------------+------------+
| foo                 |     12     |
+---------------------+------------+
```
