### ISSUE TITLE
link handling

### ISSUE THREAD

**Issue by WolfgangFahl** [astanin/python-tabulate#141]
for https://github.com/WolfgangFahl/pyLoDStorage/issues/46 i am trying to convert wikidata entity urls to proper markup links in the given tablefmt prior to using tabulate. That works o.k. for the tableformats mediawiki and github. When using latex the links are garbled since the 
```
\href{}{}
```
entries are encoded by tabulate. What would be a way to get proper links in tables with tabulate and tablefmt='latex'?

**Comment by astanin** [comment]
You can use `latexraw` format.

"latex_raw" is similar to "latex", but doesn't escape special characters,
    such as backslash and underscore, so LaTeX commands may embedded into
    cells' values:

    >>> print(tabulate([["spam$_9$", 41.9999], ["\\\\emph{eggs}", "451.0"]], tablefmt="latex_raw"))
    \\begin{tabular}{lr}
    \\hline
     spam$_9$    &  41.9999 \\\\
     \\emph{eggs} & 451      \\\\
    \\hline
    \\end{tabular}
