### ISSUE TITLE
Column width control by header name [Feature Request]

### ISSUE THREAD

**Issue by RichardForshaw** [astanin/python-tabulate#143]
I am eagerly awaiting the feature for controlling column widths which I believe is coming in the next release.

What would be great is if the column width could be controlled per-column but specified with a column name.

This is because due to up-stream data manipulation, when the input is a key-based iterable (e.g. a dict) sometimes columns may change order and you end up limiting the wrong column (if you have provided a list of widths).

Related to this, it would be good to have an option which truncated the data in the column instead of wrapping it, specifically for strings.

**Comment by astanin** [comment]
>  when the input is a key-based iterable (e.g. a dict) sometimes columns may change order

You should be using [OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict) instead of a dict if you want to fix columns order. Then you can use `maxcolwidths` option to control the maximum column widths:

```pycon
>>> from collections import OrderedDict
>>> d1 = OrderedDict(alpha = "Lorem ipsum dolor sit amet", beta = "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam")
>>> print(tabulate([d1], headers="keys", tablefmt="grid", maxcolwidths = [10, 30]))
+-----------+--------------------------------+
| alpha     | beta                           |
+===========+================================+
| Lorem     | consectetur adipiscing elit,   |
| ipsum     | sed do eiusmod tempor          |
| dolor sit | incididunt ut labore et dolore |
| amet      | magna aliqua. Ut enim ad minim |
|           | veniam                         |
+-----------+--------------------------------+
```

It works for multiline text. Numerical columns and single-line columns are shrinked to data.

> an option which truncated the data in the column instead of wrapping it

Some kind of a solution will be added in the future versions, see #171.
