### ISSUE TITLE
Cannot set `colalign` for only specific columns

### ISSUE THREAD

**Issue by stdedos** [astanin/python-tabulate#145]
I have a 4*X table, like so:

<table>
<tr>
	<td>A
	<td>B
	<td>C
	<td>D
<tr>
	<td>X
	<td>Y
	<td>1(int)
	<td>Z
<tr>
	<td>.
	<td>.
	<td>.
	<td>.
</table>

and I want to only align the 4th column to the center (without the header, but that's optional).

While it's possible to only edit the alignment of some columns on the left (leaving all the right ones "as they were"), there's no way to do it "only for a specific one that's not the first"

According to documentation, https://github.com/astanin/python-tabulate/blob/master/README.md#custom-column-alignment (https://github.com/astanin/python-tabulate/blob/b2c26bcb70e497f674b38aa7e29de12c0123708a/README.md#L436-L442)

"Omitting an alignment uses the default", but that does not seem to be the case. None of the

```python
colalign = (,,,'center')
colalign = (None,None,None,'center')
colalign = ('default','default','default','center')
colalign = ('','','','center')
```

seem to work

However, it is possible to only edit the alignment of some columns on the left leaving all the right ones "as they were" (due to the way the code is written, https://github.com/astanin/python-tabulate/blob/b2c26bcb70e497f674b38aa7e29de12c0123708a/tabulate.py#L1660-L1665, i.e. `colalign = ('center',)` etc works

**Comment by feizheng10** [comment]
The same ask!

**Comment by eliegoudout** [comment]
Solution provided in #221 : Added the `"global"` setting for specific column alignment. Thus, using `("global", "global", "left")`, only the third column would be affected. Also, from this PR, you can align headers differently, and use a `global`alignment setting.
