### ISSUE TITLE
Improper pipe formatting on blank tables with headers

### ISSUE THREAD

**Issue by Jackaloops** [astanin/python-tabulate#15]
Using tabulate v0.8.5 and python v3.6.8.

Calling tabulate with an empty data frame and header values passed in generates invalid Markdown for the `pipe` format. A call like:
```
tabulate( emptyTable, headers=emptyTable.columns.values, tablefmt="pipe", showindex=False )
```
creates the following output:
```
| col1  | col2   | col3   | col4   | col5   |
||
```

**Comment by astanin** [comment]
Two questions.

1. Does PHP Markdown and/or Pandoc fail to parse this table?

2. What is the expected output in this case? Is it something like

```
| Right | Left | Default | Center |
|------:|:-----|---------|:------:|
```

?

**Comment by Jackaloops** [comment]
1. Pandoc does not parse this table, but I haven't tested with PHP Markdown
2. Yes, that should be the output for an empty pipe table, Pandoc treats it as paragraph text otherwise.

**Comment by astanin** [comment]
It seems the easiest way to reproduce this issue is to pass an empty table with a non-empty list of columns (this is what happens when a dataframe has no data but still has column names):

```
print(tabulate.tabulate([], headers=["Col1", "Col2"], tablefmt="pipe"))
```

I'll published a fix.

**Comment by alimcmaster1** [comment]
Was this PR included in the latest release ? (On mobile so cant check myself) we are still having some issues in pandas with this ref https://github.com/pandas-dev/pandas/issues/31771

Thanks @astanin
