### ISSUE TITLE
feature request: allow optional multiline printing when data is a basic sequence

### ISSUE THREAD

**Issue by jtmoon79** [astanin/python-tabulate#153]
### problem

Currently, if an element of data is a tuple, it will be printed within one horizontal console line:

```python
import tabulate
print(tabulate.tabulate(
    [
        ("svc1.local", ("authenticator", "load_balancer")),
        ("svc2.local", ("widget_finalizer",)),
    ],
    headers=("host", "services")
))
```
prints
```text
host        services
----------  ----------------------------------
svc1.local  ('authenticator', 'load_balancer')
svc2.local  ('widget_finalizer',)
```

However, sometimes the user would prefer the tuple sequence occupy several horizontal console lines.
```text
host        services
----------  ----------------
svc1.local  authenticator
            load_balancer
svc2.local  widget_finalizer
```

### proposed feature request

Add a keyword parameter `multiline_sequence: bool`  to `tabulate.tabulate`.  If `multiline_sequence` is truthy then `tabulate.tabulate` will write any data elements that are sequences as one sequence element per horizontal console line.

Or, explained with code fragments:
given function call `tabulate.tabulate(data, multiline_sequence=True)`
for any element `x` in `data`,
if `isinstance(x, (tuple, list, set, frozenset, range))`
then write each `y for y in x` on a new console line (but part of the same table row).

<br />

For example,

```python
import tabulate
print(tabulate.tabulate(
    [
        ("svc1.local", ("authenticator", "load_balancer")),
        ("svc2.local", ("widget_finalizer",)),
    ],
    headers=("host", "services"),
    multiline_sequence=True,
))
```
prints
```text
host        services
----------  ----------------
svc1.local  authenticator
            load_balancer
svc2.local  widget_finalizer
```

<br/>

Using `tabulate` version 0.8.9.

**Comment by astanin** [comment]
I suppose that this kind of problems should be solved by custom pre-processor for your data.

```pycon
>>> data = [
...         ("svc1.local", ("authenticator", "load_balancer")),
...         ("svc2.local", ("widget_finalizer",)),
...     ]
>>> def dontrepeatcol1(data):
...     prevk = None
...     for r in data:
...         k, vs = r[0], r[1]
...         for v in vs:
...             if prevk != k:
...                prevk = k
...                yield (k, v)
...             else:
...                yield ("", v)
...
>>> list(dontrepeatcol1(data))
[('svc1.local', 'authenticator'), ('', 'load_balancer'), ('svc2.local', 'widget_finalizer')]
>>> print(tabulate(dontrepeatcol1(data), headers=("host", "services")))
host        services
----------  ----------------
svc1.local  authenticator
            load_balancer
svc2.local  widget_finalizer
```

`dontrepeatcol1` can be easily reused in your various scripts. This particular data structure is too specific to your use case to support in the library.
