### ISSUE TITLE
Multiline cells github formatting broken

### ISSUE THREAD

**Issue by rjgildea** [astanin/python-tabulate#16]
Multiline cell formatting as described in the documentation appears to be broken for the `tablefmt="github"` option. Python version 2.7.10, tabulate version 0.8.5. 

Using the following script:
```
$ cat tst.py 
from __future__ import print_function
import tabulate

print(tabulate.__version__)

table = [["eggs",451],["more\nspam",42]]
headers = ["item\nname", "qty"]

print(tabulate.tabulate(table, headers, tablefmt="github"))
```

Output:
```
$ python -V
Python 2.7.10
$ python /Users/rjgildea/software/cctbx/build/tst.py 
0.8.5
| item
name      |   qty |
|------|-------|
| eggs |   451 |
| more
spam      |    42 |
```

Expected output according to the [documentation](https://pypi.org/project/tabulate/):
```
>>> print(tabulate(table, headers, tablefmt="github"))
| item   | qty   |
| name   |       |
|--------|-------|
| eggs   | 451   |
| more   | 42    |
| spam   |       |
```

**Comment by rjgildea** [comment]
It looks like tabulate doesn't support multiline cells for `tablefmt=github`:
https://github.com/astanin/python-tabulate/blob/19da809040c2f55b657c514909573247ef1cb86f/tabulate.py#L475-L489

I suspect that is because GitHub itself doesn't appear to support multiline cells, specifically it doesn't allow more than one row in the header. I.e. the following will render:

```
| item   | qty   |
|--------|-------|
| eggs   | 451   |
| more   | 42    |
| spam   |       |
```
| item   | qty   |
|--------|-------|
| eggs   | 451   |
| more   | 42    |
| spam   |       |
But the following will not render:
```
| item   | qty   |
| name   |       |
|--------|-------|
| eggs   | 451   |
| more   | 42    |
| spam   |       |
```
| item   | qty   |
| name   |       |
|--------|-------|
| eggs   | 451   |
| more   | 42    |
| spam   |       |

However, the documentation at https://pypi.org/project/tabulate/ suggests that it multiline cells _are_ supported for `tablefmt="github"`.

**Comment by astanin** [comment]
Apparently, you're right about github not supporting multiline headers, and the code is correct. I have to remove that misleading example from the README. Thank you.
