### ISSUE TITLE
Bold the cells in the first column on Markdown formats

### ISSUE THREAD

**Issue by halloleo** [astanin/python-tabulate#169]
Firstly thanks for `tabulate`! It is inavaulable in my daily work!

Secodnly, when converting to a markdown format (like Github, etc), is it possible to set the values in the cells of the first column to bold?

I mean the following: The list `[['', 'colA', 'colB'],['row1','textA1','textB1'],['row2','textA2','textB2']]` becomes

```
|          | colA   | colB   |
|----------|--------|--------|
| **row1** | textA1 | textB1 |
| **row2** | textA2 | textB2 |
```

Note the bold `row1` and `row2` cells. - Is this possible with `tabulate`?

**Comment by astanin** [comment]
I would just pre-processed the data and added formatting to some cells before passing to tabulate. You can create a wrapper function if you need to do it frequently.

```pycon
>>> data_col1bold = [["**"+r[0]+"**" if r[0] != "" else ""]+r[1:] for r in data]
>>> print(tabulate(data_col1bold, headers="firstrow", tablefmt="github"))
|          | colA   | colB   |
|----------|--------|--------|
| **row1** | textA1 | textB1 |
| **row2** | textA2 | textB2 |
```

I don't want to add it to the library. It's a very specific use case, and it doesn't translate well to other table formats.

**Comment by halloleo** [comment]
Fair enough, @astanin.

BTW, I like your nice and concise list comprehension to bold the values in the first column! 😊
