### ISSUE TITLE
Multi-line cells with github formatting

### ISSUE THREAD

**Issue by edporteous** [astanin/python-tabulate#17]
The multi-line formatting for github tables doesn't appear to be correct:

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32   
Type "help", "copyright", "credits" or "license" for more information.                        
>>> from tabulate import tabulate
>>> table = [["eggs",451],["more\nspam",42]]
>>> print(tabulate(table, tablefmt="github"))
|-----------|-----|
| eggs      | 451 |
| more
spam |  42 |
>>>
```

I get the same output for Python 3.8.0.

**Comment by astanin** [comment]
The same issue as in #16. Apparently, [github flavored markdown spec](https://github.github.com/gfm/) does _not_ specify multiline cells and the site does not render them correctly:


|col1|col2|
|-----------|-----|
| eggs      | 451 |
| more
spam |  42 |

`github` was erroneously listed as a format which supports multiline table cells. This paragraph was removed from the README.
