### ISSUE TITLE
Expose eventual column widths

### ISSUE THREAD

**Issue by mhuang001** [astanin/python-tabulate#174]
Please expose eventual widths of columns. This is part of `git diff` of my hack
<pre>
@@ -1673,2 +1690,4 @@ def tabulate(
 
+    global EVENTUAL_WIDTHS
+
     if headers:
@@ -1685,2 +1704,6 @@ def tabulate(
         ]
+
+        EVENTUAL_WIDTHS = [width_fn(h) for h in headers]
+        #print('**********', EVENTUAL_WIDTHS, headers)
+
         rows = list(zip(*cols))
@@ -1688,2 +1711,6 @@ def tabulate(
         minwidths = [max(width_fn(cl) for cl in c) for c in cols]
+
+        EVENTUAL_WIDTHS = minwidths
+        #print('==========', EVENTUAL_WIDTHS, minwidths)
+
         rows = list(zip(*cols))
</pre>
then one could, for example, show headers `['col1', 'col2', 'group1.val', 'group1.err', 'no-group.val', 'group2.val', 'group2.err', 'group2.seq', 'group2.wgt']
` in two rows by making a table, getting the column widths from `tabulate.EVENTUAL_WIDTHS,`,  making another table of  combined columns, and pasting the header to the original table
<pre>
+-----------------+-----------------+--------+----------------------------------------+
|                 |     group1      |  no-   |                 group2                 |
|                 |                 | group  |                                        |
+--------+--------+--------+--------+--------+--------+--------+--------+-------------+
|   col1 |   col2 |    val |    err |    val |    val |    err |    seq | wgt         |
+========+========+========+========+========+========+========+========+=============+
|    1   |    0   |    1   |    0   |    1   |    1   |    0   |    0   |             |
+--------+--------+--------+--------+--------+--------+--------+--------+-------------+
|    4.4 |   43.2 |    4.4 |   43.2 |    4.4 |    4.4 |   43.2 |   43.2 | 0.32        |
+--------+--------+--------+--------+--------+--------+--------+--------+-------------+
| 5400   | 2000   | 5400   | 2000   | 5400   | 5400   | 2000   | 2000   | -9876543210 |
+--------+--------+--------+--------+--------+--------+--------+--------+-------------+
</pre>
Thanks.

**Comment by astanin** [comment]
You use case seems to be very specific. I suggest to keep changes in the private fork.

I don't like writing function output to global variables.

What can be done at some point is to have a function parameter which allows to enforce some specific column widths.
