### ISSUE TITLE
Join vertical lines in fancy_grid format

### ISSUE THREAD

**Issue by baterflyrity** [astanin/python-tabulate#177]
Hi there!

Is there a way to join vertical lines in one solid vertical border (remove vertical spacing) in fancy_grid format?

**Comment by kdeldycke** [comment]
Can you show us what would you like your table to look like? I suspect what you're trying to achieve might have been implemented in #151.

**Comment by baterflyrity** [comment]
It is a pitty, but it seems to be truth. Can you recommend fonts to render grid fancy?
