### ISSUE TITLE
Allow to specify the same colalign with only one argument:

### ISSUE THREAD

**Issue by astanin** [astanin/python-tabulate#182]
The desired behavior:

```
>>> print(tabulate([[1, 2], [345, 67890]], colalign="center", tablefmt="grid"))
+-----+-------+
|  1  |   2   |
+-----+-------+
| 345 | 67890 |
+-----+-------+
```

IndexError in the current version.

**Comment by astanin** [comment]
To check if it's backwards compatible.

**Comment by eliegoudout** [comment]
I think it would be confusing with the enhancement proposed in #221. There, it is proposed to have both a global setting and a column-wise setting.
