### ISSUE TITLE
Way to reverse a tabulated string

### ISSUE THREAD

**Issue by i-am-zaidali** [astanin/python-tabulate#188]
Basically I'm receiving some data from a source that uses this package to tabulate the said data. Now i need to parse the data to the form it was originally in but I can't think of a way and str.split and relevant methods aren't proving very useful. Is there a way I can parse a tabulated string to get the originally passed data?

**Comment by astanin** [comment]
You cannot do it with a library. Probably your  best chance is to write a custom parse code or use a software like Pandoc which can transform it to some other format which is easier to process.
