### ISSUE TITLE
Can't print bytes with non-ascii encoding

### ISSUE THREAD

**Issue by linuxlc** [astanin/python-tabulate#192]
example:
```python
print(tabulate([["你好".encode("utf-8"), "你好"]], headers=["bytes", "str"]))
```

Currently, an UnicodeDecodeError will be raised:

```text
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

Related code is here:
https://github.com/astanin/python-tabulate/blob/3f0757e117ed2ca1171bbf84b61793f353d67282/tabulate.py#L1070

As I understand it, an UnicodeDecodeError should be caught instead of a TypeError, right?
So output would be like:
```text
bytes                        str
---------------------------  -----
b'\xe4\xbd\xa0\xe5\xa5\xbd'  你好
```
I'm not sure if it's the designed behavior, but i think it's a proper way to handle non-ascii bytes.
Furthermore, why not return all bytes as str(val) directly without trying to return str(val, "ascii") at first? If the caller want to print decoded value, they can decode it explicitly before calling tabulate().

**Comment by FurcyPin** [comment]
+1 
Ran into the same issue, and replacing TypeError with UnicodeDecodeError works in my case too.
Perhaps we should catch both type of errors, though ?

**Comment by FurcyPin** [comment]
I made a [pull request](https://github.com/astanin/python-tabulate/pull/196) to fix the issue.
