### ISSUE TITLE
Extra Whitespace in GitHub Table Format

### ISSUE THREAD

**Issue by sortedcord** [astanin/python-tabulate#195]
I couldn't help but notice that tabulate adds extra padding for thinner columns when using GitHub table format. The difference might be subtle, but it is there..
Here is an example:

Original
```
| S.No.   | File Size   |
|---------|-------------|
| 00      | 4.2 MB      |
| 01      | 43.8 MB     |
| 02      | 3.5 MB      |
| 03      | 14.5 MB     |
| 04      | 1.5 MB      |
````

Without Whitespace
```
| S.No. | File Size |
|-------|-----------|
| 00    | 4.2 MB    |
| 01    | 43.8 MB   |
| 02    | 3.5 MB    |
| 03    | 14.5 MB   |
| 04    | 1.5 MB    |
```

Am I missing out on something or is there any way to disable this. I can't seem to find a workaround for this..

**Comment by smprather** [comment]
I am also here to find a way to trim the horizontal padding (simple format for me). Are there any PRs outstanding for this? If not, I can take a shot at adding a horizontal cell padding parameter.

```
power_type             ref       test    abs_delta    rel_delta(%)
---------------  ---------  ---------  -----------  --------------
total_power      0.0249900  0.0237600   -0.0012300           -4.92
switching_power  0.0233700  0.0221900   -0.0011800           -5.05
internal_power   0.0015550  0.0014990   -0.0000560           -3.60
leakage_power    0.0000687  0.0000679   -0.0000008           -1.14
```
Preferred
```
power_type            ref      test  abs_delta rel_delta(%)
--------------- --------- --------- ---------- ------------
total_power     0.0249900 0.0237600 -0.0012300        -4.92
switching_power 0.0233700 0.0221900 -0.0011800        -5.05
internal_power  0.0015550 0.0014990 -0.0000560        -3.60
leakage_power   0.0000687 0.0000679 -0.0000008        -1.14
```

**Comment by sortedcord** [comment]
Well, I was able to fix this, but it isn't very pretty. https://github.com/sortedcord/python-tabulate/blame/master/tabulate.py made 2 edits basically hardcoded padding=0 at 2 places one for the headings and other for the data rows, and it did work. There were no extra whitespaces. Although, it I am pretty sure there is a better way of handling this...

**Comment by astanin** [comment]
Horizontal padding is required in some formats to indicate horizontal alignment (left/centered/right). So that's where padding comes initially.

You can reduce padding like this:

```pycon
>>> import tabulate as t
>>> t.MIN_PADDING = 0
>>> print(t.tabulate([[1,22],[33,4]], headers=["aa","bb"], tablefmt="simple"))
aa  bb
--  --
 1  22
33   4
```
