### ISSUE TITLE
Ellipisis instead of newline for maxcolwidths

### ISSUE THREAD

**Issue by yashagacisco** [astanin/python-tabulate#229]
When specifying the max width of column, it would be nice to have an option to truncate (with ellipsis) the entry instead of a newline. 

For eg `["foo bar fooooooooo", 5 ,6]` resulting in:
`foo bar foo...    5     6`

**Comment by bramp** [comment]
This was closed, but it's not obvious if there was a solution, doing the following:

```python
    print(tabulate(data, maxcolwidths=[10]))
```

Seems to wrap at 10 characters. How can we truncate (optionally with a ellipisis)?
