### ISSUE TITLE
Adding a SEPARATING_LINE fails, for any format with padding

### ISSUE THREAD

**Issue by pjkundert** [astanin/python-tabulate#246]
If a format with padding is used, the test for SEPARATING_LINE fails, resulting in a table containing an (unprintable) \x01 character instead of a separating line.

This is because the padding is applied before the test for SEPARATING_LINE.  The row now contains " \x01 ", instead of "\x01", so the test fails.

However, since multi-line cells are post-padded, the test succeeds, and a separating line is added!

So, instead of pre-padding the rows, always pad them immediately before output.

**Comment by astanin** [comment]
I tried merging this commit with master (see pr-279 branch), but the tests fail in test_simple_headerless_with_sep_line_with_linebetweenrows_in_tablefmt.

Expected output:

```
+------+----------+
| spam |  41.9999 |
+------+----------+
+------+----------+
| eggs | 451      |
+------+----------+
```

actual output:

```
+------+----------+
| spam |  41.9999 |
+------+----------+
||
+------+----------+
| eggs | 451      |
+------+----------+
```
