### ISSUE TITLE
README includes features which are not released yet (colglobalalign, headersglobalalign)

### ISSUE THREAD

**Issue by graysonpike** [astanin/python-tabulate#274]
Currently, the README includes features such as `colglobalalign` and `headersglobalalign` that appear to have been contributed shortly after version 0.9.0 was released and published to pip.

This causes confusion for users. For example, I assumed that these features were available in the most recent release 0.9.0 and was confused when my interpreter failed to find these arguments.

Only by looking at the timestamps of commits to the README did I learn that these features are not included in version 0.9.0.

**Comment by eliegoudout** [comment]
Hello,
Which README are you referring to?
Because I think the one from [PyPi](https://pypi.org/project/tabulate/) doesn't show these arguments.

**Comment by graysonpike** [comment]
Hi @eliegoudout, you're right, and apologies for the confusion. I was referring to the README on the master branch of this repository.

I had assumed that master held released code, and a development branch would hold stable unreleased code. Hence me reading the README from `master`.

I'm closing this issue now that I know to read from PyPi instead. Thanks!
