### ISSUE TITLE
It seems the 0.9.0 version in PyPI is not the same as the current one in this repo

### ISSUE THREAD

**Issue by flcong** [astanin/python-tabulate#276]
For example, in the one downloaded from [PyPI](https://pypi.org/project/tabulate/#files), `tabulate()` does not have arguments `headersglobalalign` or `headersalign`.

**Comment by eliegoudout** [comment]
The doc from github is ahead of PyPi's release. If you install from PyPi, you should refer to its own doc.
See #274.

Cheers!

**Comment by flcong** [comment]
Thanks!
