### ISSUE TITLE
Corrupts Application

### ISSUE THREAD

**Issue by fewei** [astanin/python-tabulate#31]
Hi,
I have a bug that breaks the whole application. (python 3.7, tabulate 0.8.6)

I removed as much code and table text as possible.
[crash.py](https://github.com/astanin/python-tabulate/files/4006601/crash.zip)
```python
from tabulate import tabulate
table = [
    ['1295-kein_.pdf', ''],
    ['Ausrüstungsliste', '']]
print(tabulate(table))
print('Executed')
import json
print('Not executed')
```
My output
```
----------------
1295-kein_.pdf
Ausrüstungsliste
----------------
Executed

Process finished with exit code -1073741819 (0xC0000005)
```

**Comment by astanin** [comment]
I ran your code, it's OK. It appears you have a problem in `import json`. Please make sure you can run

```
python -c 'import json'
```

Make sure you don't have json.py or json folder in the same directory which Python may consider a module.
