### ISSUE TITLE
Migrate to pytest since nose is Python 3.9 incompatible

### ISSUE THREAD

**Issue by tirkarthi** [astanin/python-tabulate#35]
nose is not maintained and is incompatible with Python 3.9 as reported in https://github.com/nose-devs/nose/issues/1099 . Using pytest seems to be a better option and testing with nose will become an issue with Python 3.9 .

**Comment by astanin** [comment]
Resolved in dfaa28bd180db52ba50d777d32c8764bdb1883b4
