### ISSUE TITLE
[REQ] Modifiers (such as ANSI escape) that can change per row as part of Data rows

### ISSUE THREAD

**Issue by WPettersson** [astanin/python-tabulate#38]
I'm looking for something to print pretty tables for me for a project. tabulate seems to do 95% of what I want, with the exception that I want to change the background colours for some rows. Mostly, I want to alternate between white, and light-grey backgrounds, but I'd also like the ability to highlight certain rows, and with this in mind, maybe my ideal is to be able to add a function to the DataRow constructor, get_colour, such that for each row of data, get_colour(row) is run and the returned value is used to colour the row.

The actual colouring is doable with ANSI escape codes, I've already got them running for bold/underlines/foreground/backgrounds, but I have to treat each data row identically.

The way I see this working is the DataRow constructor has the optional get_colour parameter. If present, and a function, it is called on each row in turn, and the result is used to colour the row.
If one value is returned, use it to choose the colour of the font. If two values are returned (in a list), the first (if not None) is the foreground, and the second (if not None) is the background.

Each TableFormat would also have to have a "colour_encode" function. For instance, for ANSI escape codes, there'd first have to be a colour lookup (string name to integer), and then it would return \033]38;5;X or similar. There'd also need to be a "end colour" method, to reset colours. For HTML, the equivalent might be a closing tag.

I don't know if this is something this project wants. It's a lot of extra features and code for something that very few people (maybe only me) would use. If the project thinks it might be interesting, I'll happily write something, but otherwise I might just use the parts of tabulate that I want directly in my project.

Does this sound useful to others?

**Comment by astanin** [comment]
As you put it,

> It's a lot of extra features and code for something that very few people (maybe only me) would use.

I suppose the best way to go is to develop a custom TableFormat, where formatting of the rows is handled by a custom function. See how `latex`, `textile` and `mediawiki` formats are implemented. To achieve alternating colours the formatting function would have to update an (effectively global) counter.

Something along the lines of:

```
In [1]: class Counter(object):
   ...:     c = 0
   ...:     def countme(self):
   ...:         self.c += 1
   ...:         return self.c
   ...:

In [2]: cobj = Counter()

In [3]: cobj.countme()
Out[3]: 1

In [4]: cobj.countme()
Out[4]: 2
```

I don't think this custom TableFormat will find its way into the main library, but TableFormat structure didn't change for a long time. So it shouldn't be much hassle to support.

**Comment by WPettersson** [comment]
Thanks for the advice on that, I'll see if I can get what I want working on my end, and will report back if there's anything interesting worth mentioning.
