### ISSUE TITLE
Support hyperlinks encoded as terminal escape sequences

### ISSUE THREAD

**Issue by michael-plutoflume** [astanin/python-tabulate#39]
Some terminals support [clickable text](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) via escape sequences. If we use the escape sequence

```python
>>> import tabulate
>>>
>>> def encode_url(text: str, target:str):
...     return f"\u001b]8;;{target}\u001b\\{text}\u001b]8;;\u001b\\"
... 
>>> table = tabulate.tabulate([[encode_url("test", "http://example.org")]], headers=["test"], tablefmt="grid")
>>> print(table)
+--------+
| test   |
+========+
| test        |
+--------+
```

tabulate does not calculate the width correctly.

**Comment by astanin** [comment]
Never heard of it. A pull request with an implementation and tests to make sure it covers all cases would be welcome.

**Comment by jquast** [comment]
https://blessed.readthedocs.io/en/latest/terminal.html#hyperlinks
https://github.com/jquast/blessed/blob/master/blessed/terminal.py#L871-L895
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
