### ISSUE TITLE
HTML format with grid

### ISSUE THREAD

**Issue by arielszabo** [astanin/python-tabulate#44]
The  existing "html" tablefmt produces good html tables but the are missing a border:

![image](https://user-images.githubusercontent.com/29309980/76537492-84862300-6486-11ea-9706-1a6cf292fec6.png)

Maybe a good idea will be to add a "grid_html" tablefmt to produce the exact same table but with borders:
![image](https://user-images.githubusercontent.com/29309980/76537993-450c0680-6487-11ea-981b-3be1e7971e2b.png)

**Comment by arielszabo** [comment]
pull request #45

**Comment by astanin** [comment]
IMO HTML is a kind of format which allows to separate content and representation. There is no need to include all possible styles of the HTML tables in the tabulate library, when they can be easily modified/set by the styles of the HTML document where the table is supposed to be used.

**Comment by rishabh-vij** [comment]
this was a good add on maybe. tables without grids generally look ugly in email

**Comment by ZKeeer** [comment]
replace <table> with <table border='1'> in result, maybe better.
