### ISSUE TITLE
0.8.7 broke html rows in tables

### ISSUE THREAD

**Issue by harlowja** [astanin/python-tabulate#48]
So I have an application which is doing the proper html escaping of row items.

In the new 0.8.7 release it seems now those rows are getting html escaped automatically in html tables.

Is there anyway we can make the html escaping an option that can be turned off (default to on) so that people that know what they are doing can include html in tables without issue...

**Comment by astanin** [comment]
Thank you for the reporting this issue. This change probably should not have been released in a minor release.

We have two options now:

 - add a 'unsafehtml' format
 - revert 'html' to be non-escaping, and add a 'safehtml' format

Do you have any preference on this matter?

**Comment by harlowja** [comment]
I think a 'unsafehtml' would be ok. For folks that are doing there own html escaping that I think would be fine.

**Comment by astanin** [comment]
OK, I merged `unsafehtml` pull request. To be available in 0.8.8.

**Comment by harlowja** [comment]
Much appreciated!

**Comment by maartenbreddels** [comment]
Awesome library, and I also got hit buy this bug. Can I suggest using semver, and tag a 1.0.0 release so it is more clear when breaking versions occur. Pre 1.0.0 is getting out of favour in some circles because of this, and I think tabulate deserves a 1.0.0 :)
