### ISSUE TITLE
Feature Request: Transpose

### ISSUE THREAD

**Issue by lukasc-ch** [astanin/python-tabulate#54]
Sometimes it would be great to transpose the table to fit it into a certains width. This happens particularly often when plotting multiple time series (e.g. with pyplot.plot(...)). In that case, being able to transpose the table would be a helpful addition. 

In its basic form, this is a one-liner: data = zip(*data)
However, it becomes more verbose when considering headers, etc. and would just be a convience feature. Presumably, the debat is whether this should be done before, outside tabulate. 
The change is minimal, let me know if you would like to have a pull request.

**Comment by astanin** [comment]
Yes, this kind of data processing should be done outside of tabulate. Some tabular data sources can do it differently, and probably more efficiently. I also feel that this will bring more confusion about how the library works. So it might be a convenience for some, maintenance burden for me, and probably another barrier for potential contributors and new users.
