### ISSUE TITLE
implicit Float styling reformat applied on string values

### ISSUE THREAD

**Issue by pete312** [astanin/python-tabulate#60]
Ive had this issue with strings being reformated by tabulate.

```
>>> sample =  [[f"{1.202:0.2f}",f"{1.212:0.2f}"]]
>>> sample
[['1.20', '1.21']]

```
We have a sample of 2 strings that were formatted from 2 floats to make two '0' padded strings

after tabulate we have truncation of the 0 padding on the 1st string.  

```
>>> print(tabulate(sample))
---  ----
1.2  1.21
---  ----
```

Its probably minor but I don't think it should do that on a string value.  So I would mark it as a bug. Otherwise I like it on small result sets.

**Comment by rchaves33** [comment]
I can confirm this bug. Encountered it today.

**Comment by astanin** [comment]
It's the same issue, any text which can be parsed as a number is converted to a number, and then default formatting is applied.

When the user has pre-formatted numbers, use `disable_numparse` option:

```
>>> sample =  [[f"{1.202:0.2f}",f"{1.212:0.2f}"]]
>>> tabulate(sample, disable_numparse=True)
'----  ----\n1.20  1.21\n----  ----'
>>> print(_)
----  ----
1.20  1.21
----  ----
```
