### ISSUE TITLE
Bug: implicit conversion of strings to exponent. (tabulate converting types)

### ISSUE THREAD

**Issue by pete312** [astanin/python-tabulate#66]
This is a bug is converting strings like this  20200407_2  to exponent values.
 
```
>>> print(tabulate.tabulate([ [93, '20200310.2'], [65, '20200407_2'] ]))
--  -----------
93  2.02003e+07
65  2.02004e+08
--  -----------
```

surprising that float will convert this one at all as it has an underscore in it. 
```
>>> float('20200407_2')
202004072.0
```

Anyway tabulate should not be converting types at all.

**Comment by MikeBusuttil** [comment]
I have the same issue where the trailing decimal value is removed if it's zero.
```
>>> print(tabulate([['temperature', '18.0', '0.5', '°C']], ['measurement', 'value', 'uncertainty', 'units'], tablefmt="psql"))
+---------------+---------+---------------+---------+
| measurement   |   value |   uncertainty | units   |
|---------------+---------+---------------+---------|
| temperature   |      18 |           0.5 | °C      |
+---------------+---------+---------------+---------+
```
I assume this is meant to be a feature but in our lab this is a bug (as it implies we know less significant digits than we do).
Please let me know if there's a way to suppress the type conversion.
Also, if handling/converting numbers if this is a feature that is meant to be included in the tabulate library you might consider implementing it with help of the [sigfig](https://sigfig.readthedocs.io) library.

**Comment by MikeBusuttil** [comment]
@pete312 I was able to fix the issue by invoking the disable_numparse argument:
```print(tabulate.tabulate([ [93, '20200310.2'], [65, '20200407_2'] ], disable_numparse=True))```

**Comment by pete312** [comment]
Nice one @MikeBusuttil that does work. This should default to True in my humble opinion. OK Nothing for it then but to make one of these gadgets at import to invert things else I'll forget to do it at some point.
```
import tabulate as _tabulate
tabulate = lambda *a, disable_numparse=True, **ka: _tabulate.tabulate(*a, disable_numparse=disable_numparse, **ka)

>>> print(tabulate([ [93, '20200310.2'], [65, '20200407_2'] ]))
--  ----------
93  20200310.2
65  20200407_2
--  ----------
>>> print(tabulate([ [93, '20200310.2'], [65, '20200407_2'] ],disable_numparse=False))
--  -----------
93  2.02003e+07
65  2.02004e+08
--  -----------


>>> print(tabulate([['temperature', '18.0', '0.5', '°C']], ['measurement', 'value', 'uncertainty', 'units'], tablefmt="psql"))
+---------------+---------+---------------+---------+
| measurement   | value   | uncertainty   | units   |
|---------------+---------+---------------+---------|
| temperature   | 18.0    | 0.5           | °C      |
+---------------+---------+---------------+---------+

```

**Comment by astanin** [comment]
Nice workaround, @pete312. Yes, it's not a bug, it's a feature.

You use case may be different, but I originally wrote tabulate because I didn't want to handle conversion of strings to numbers manually. So for me, personally, it's a reasonable default. And my gut feeling tells me that your use case is less common. At this point the default cannot be changed, because it would be a breaking change for many users.

What can be done, the module can export another function name, which can be wrapper like you suggested, with different defaults. But we have to think twice who exactly its users are, and why would they use a wrapper instead. Do they want full control? What other defaults have to be changed? Should it have no defaults at all?

**Comment by pete312** [comment]
@astanin The end point of tabulate is text align and is display only.  Auto convert int to str is fine but going back is not consistent in regression.  Meaning tabulate will output different results python 3.6 than prior versions of python 3. because python 3.6 allows an int to be defined as 20200407_2 and not before 3.6. However "20200407_2" and 20200407_2 are not equal.  Also the output of print("20200407_2") is not the same.

```
>>> 20200407_2 == "20200407_2"
False
>>> print(20200407_2), print("20200407_2")
202004072
20200407_2
(None, None)
```

To me this means tabulate is incorrectly converting a previously string type to an int type.  Output will differ after 3.6 with this default set to True. It will not break if set to False.  Usually regression test failure are considered as bugs.  "Undefined behavior" or "Inconsistant Feature"
