### ISSUE TITLE
Feature request: Insert a divider

### ISSUE THREAD

**Issue by matthewlloyd** [astanin/python-tabulate#72]
It would be great to be able to add a dividing line at arbitrary points within a table. For example:

```python
import tabulate

rows = []
rows.append([1, 2, 3])
rows.append([4, 5, 6])
rows.append(tabulate.DIVIDER)
rows.append([5, 7, 9])
print(tabulate.tabulate(rows, tablefmt='psql'))
```

Desired output:

```
+---+---+---+
| 1 | 2 | 3 |
| 4 | 5 | 6 |
+---+---+---+
| 5 | 7 | 9 |
+---+---+---+
```

**Comment by astanin** [comment]
This is the same as #69 Feature Request: Support for "footer" or "total" row

**Comment by matthewlloyd** [comment]
This is not the same request, because the divider could be inserted at any arbitrary row in the table, not just to separate the last row.

**Comment by habibrahmanbd** [comment]
> This is the same as #69 Feature Request: Support for "footer" or "total" row

I don't think he is asking the same thing. It's not a total/summation row. He is asking for a divider in the middle of the table. I think between rows.

**Comment by matthewlloyd** [comment]
> I don't think he is asking the same thing. It's not a total/summation row. He is asking for a divider in the middle of the table. I think between rows.

Exactly. The divider might be used to separate sections within the table, or to separate a footer with multiple rows. Drawing a divider before a single last row is _one_ possible use case, but it would be great to have something more general.

**Comment by BartBruh** [comment]
Use SEPARATING_LINE after importing it as `from tabulate import SEPARATING_LINE`

I don't know if this feature existed when it was requested but figured I would reply just in case somebody else stumbles here while searching for it.

Example:
`from tabulate import tabulate, SEPARATING_LINE`
`data = [
    ['Jack', 'Word 1', 'Word 2'],
    ['Ronaldinho', 'Word 3', 'Word 4'],
    SEPARATING_LINE,
    ['Becky', 8, 9],
    ['William', 1, 2]
]`
`print(tabulate(data))`

The output will have a line break in place of the SEPARATING_LINE.
```----------  ------  ------
Jack        Word 1  Word 2
Ronaldinho  Word 3  Word 4
----------  ------  ------
Becky       8       9
William     1       2
----------  ------  ------`
