### ISSUE TITLE
Doesnt work properly for python series

### ISSUE THREAD

**Issue by armando-fandango** [astanin/python-tabulate#73]
In tabulate.py line 1033: rows = [list(row) for row in vals]
if a series is passed then row is not a list.
Fix: rows = [list(row) if isinstance(row, (list,tuple,set)) else [row] for row in vals]

**Comment by astanin** [comment]
Pandas Series can be converted to a DataFrame, which tabulate is happy to print:

```
>>> d = {'a': 1, 'b': 2, 'c': 3}
>>> ser = pd.Series(data=d, index=['a', 'b', 'c'])
>>> ser
a    1
b    2
c    3
dtype: int64
>>> print(tabulate(ser.to_frame(), tablefmt="grid"))
+---+---+
| a | 1 |
+---+---+
| b | 2 |
+---+---+
| c | 3 |
+---+---+
```

**Comment by astanin** [comment]
Given there's an easy workaround, I don't think the fix is necessary.
