### ISSUE TITLE
Pretty format doesnt correspond with docs

### ISSUE THREAD

**Issue by boudewijnk** [astanin/python-tabulate#75]
The table produced with the pretty format does not look like the table presented in the README file.

When I run the following code:
```
from tabulate import tabulate
table = [["spam",42],["eggs",451],["bacon",0]]
headers = ["item", "qty"]
print(tabulate(table, headers, tablefmt="pretty"))
```

I get:
```
item      qty
------  -----
spam       42
eggs      451
bacon       0
```

Instead of:
```
+-------+-----+
| item  | qty |
+-------+-----+
| spam  | 42  |
| eggs  | 451 |
| bacon |  0  |
+-------+-----+
```

**Comment by eldipa** [comment]
Hi @boudewijnk, I checked locally (with `tabulate` version `'0.8.7'`) and I'm seeing the correct output for `pretty`:

```
+-------+-----+
| item  | qty |
+-------+-----+
| spam  | 42  |
| eggs  | 451 |
| bacon |  0  |
+-------+-----+
``` 

Could you check what version of `tabulate` do you have installed and if the issue still exists?

**Comment by boudewijnk** [comment]
I don't know which version I had installed in August. 
With the most recent version of tabulate (0.8.7), code works as expected. Can be closed.
