### ISSUE TITLE
Improve error message when passing too many entries in colalign

### ISSUE THREAD

**Issue by alexwlchan** [astanin/python-tabulate#84]
I'm using tabulate 0.8.7.

Consider the following example:

```python
from tabulate import tabulate

print(
    tabulate(
        [("square", 4), ("triangle", 3), ("circle", 1)],
        headers=["name", "sides"],
        colalign=("left", "right", "right"),
    )
)
```

If I run that code, I get an error, and it's not immediately clear what I've done wrong:

```
Traceback (most recent call last):
  File "s.py", line 4, in <module>
    tabulate(
  File "/usr/local/lib/python3.8/site-packages/tabulate.py", line 1494, in tabulate
    aligns[idx] = align
IndexError: list assignment index out of range
```

Digging a little further, I notice I only have two columns, but three entries in `colalign`. Oops!

It'd be nice if this provided a more explicit error message. Something like:

```diff
     # align columns
     aligns = [numalign if ct in [int, float] else stralign for ct in coltypes]
     if colalign is not None:
         assert isinstance(colalign, Iterable)
+        if len(colalign) > len(aligns):
+            raise ValueError(
+                "There are %d alignment(s) in colalign=%r, but only %d column(s)" %
+                (len(colalign), colalign, len(coltypes))
+            )
         for idx, align in enumerate(colalign):
             aligns[idx] = align
```

(Although note this doesn't cover all cases: `colalign` is guaranteed to be an `Iterable`, but not a `Sized`, so it might not have a `__len__()` method to call. You could try a different `if` statement, or maybe catch the IndexError.)

**Comment by astanin** [comment]
I can confirm this in 0.8.8, and agree this is a bug.

**Comment by eliegoudout** [comment]
Problem was fixed by ignoring too many `colalign` entries in #221
