### ISSUE TITLE
[Feature Request] csv/xlsx

### ISSUE THREAD

**Issue by X-C0DE** [astanin/python-tabulate#85]
Please
Also add an output option to a spreadsheet. This will help other people too, not just like me :smiley:

**Comment by behrens-cloud** [comment]
CSV would be good to have - that way, one can support simple interfaces to export to HTML, text, or to CSV.  From a web page, just a simple mime type of text/csv should cause browser to open correct app.

**Comment by astanin** [comment]
Won't fix. See explanation for issue #55.
