### ISSUE TITLE
Wordwrap with long lines of text for a specific column

### ISSUE THREAD

**Issue by koustubh25** [astanin/python-tabulate#90]
I have the following code:

```
results = [('test', 'PR skipped', '428 A PR from test to develop is already open. Please close/merge it before you run this script. And some more text..  Skipping this module...')]
headers=("Module Name", "Result", "Comment")
print(tabulate(results,  headers, tablefmt="grid"))   
```
and produces this

![image](https://user-images.githubusercontent.com/5240529/94652486-7540c700-033d-11eb-9e54-80bab8ad4f45.png)

is there a way I can wrap text in the last column?

**Comment by astanin** [comment]
It's a feature I used to think about, and one day it may get implemented. Basically, `tabulate()` function will need an extra parameter with a list of column widths. Something like this:

```
print(tabulate(results, headers, tablefmt="grid", colwidths=[20, 20, 40]))
...
```

Meanwhile this effect can be easily achieved by using [`textwrap`](https://docs.python.org/3/library/textwrap.html) module directly, which is part of the standard library. It is as easy as writing two lines of code if you want to wrap all columns:

```
colwidths = [20, 20, 40]
results_wrapped = [[textwrap(cell,w) for w,cell in zip(colwidths, row)] for row in results]
```

And the result is what you want:

```
>>> print(tabulate(results_wrapped, headers, "grid"))
+---------------+------------+------------------------------------------+
| Module Name   | Result     | Comment                                  |
+===============+============+==========================================+
| test          | PR skipped | 428 A PR from test to develop is already |
|               |            | open. Please close/merge it before you   |
|               |            | run this script. And some more text..    |
|               |            | Skipping this module...                  |
+---------------+------------+------------------------------------------+
```

You get the idea.

**Comment by astanin** [comment]
Just in case anybody wants to contribute this feature, these are some of the tests to be implemented:

- colwidths parameter can be specified as a number (the same for all column)
- colwidths parameter can be shorter than the number of column (don't wrap text in the remaining columns)
- the feature works when all columns are text
- the feature works when some columns are numeric
- the feature works when some columns contain wide characters (Japanese/Chinese/Korean)
- the feature works when some columns contain invisible control characters (ASCII escape codes, color, hyperlinks)
- the feature works reasonably well or is disabled in formats which cannot support it (HTML? LaTeX?)
- when bidirectional script support is implemented first, this feature should work correctly when there's mixed left-to-right and right-to-left text in a cell (English + Arabic/Hebrew/...)

**Comment by magelisk** [comment]
FYI, I had a need for this so have implemented most of this so far. Will plan on a PR in in the next few days. You're welcome to look at it early if desired. https://github.com/astanin/python-tabulate/compare/master...magelisk:90-automatic-wordwrap?expand=1

**Comment by AtomicNess123** [comment]
> row

Hi, I don't

> It's a feature I used to think about, and one day it may get implemented. Basically, `tabulate()` function will need an extra parameter with a list of column widths. Something like this:
> 
> ```
> print(tabulate(results, headers, tablefmt="grid", colwidths=[20, 20, 40]))
> ...
> ```
> 
> Meanwhile this effect can be easily achieved by using [`textwrap`](https://docs.python.org/3/library/textwrap.html) module directly, which is part of the standard library. It is as easy as writing two lines of code if you want to wrap all columns:
> 
> ```
> colwidths = [20, 20, 40]
> results_wrapped = [[textwrap(cell,w) for w,cell in zip(colwidths, row)] for row in results]
> ```
> 
> And the result is what you want:
> 
> ```
> >>> print(tabulate(results_wrapped, headers, "grid"))
> +---------------+------------+------------------------------------------+
> | Module Name   | Result     | Comment                                  |
> +===============+============+==========================================+
> | test          | PR skipped | 428 A PR from test to develop is already |
> |               |            | open. Please close/merge it before you   |
> |               |            | run this script. And some more text..    |
> |               |            | Skipping this module...                  |
> +---------------+------------+------------------------------------------+
> ```
> 
> You get the idea.

I tried this but it spits an error:` TypeError: 'module' object is not callable`
I defined row = len(results)

**Comment by bencwallace** [comment]
> > It's a feature I used to think about, and one day it may get implemented. Basically, `tabulate()` function will need an extra parameter with a list of column widths. Something like this:
> > ```
> > print(tabulate(results, headers, tablefmt="grid", colwidths=[20, 20, 40]))
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Meanwhile this effect can be easily achieved by using [`textwrap`](https://docs.python.org/3/library/textwrap.html) module directly, which is part of the standard library. It is as easy as writing two lines of code if you want to wrap all columns:
> > ```
> > colwidths = [20, 20, 40]
> > results_wrapped = [[textwrap(cell,w) for w,cell in zip(colwidths, row)] for row in results]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the result is what you want:
> > ```
> > >>> print(tabulate(results_wrapped, headers, "grid"))
> > +---------------+------------+------------------------------------------+
> > | Module Name   | Result     | Comment                                  |
> > +===============+============+==========================================+
> > | test          | PR skipped | 428 A PR from test to develop is already |
> > |               |            | open. Please close/merge it before you   |
> > |               |            | run this script. And some more text..    |
> > |               |            | Skipping this module...                  |
> > +---------------+------------+------------------------------------------+
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You get the idea.
> 
> I tried this but it spits an error:` TypeError: 'module' object is not callable`
> I defined row = len(results)

You're probably calling `textwrap` when you should be calling `textwrap.wrap`.

**Comment by AtomicNess123** [comment]
Thanks! OK, I see. My results is actually a dataframe: `results=pd.DataFrame(results)`.
How could I make it work in my case? 
The table I get looks like this:


```
+-------+-------+-------+-------+-------+
| 0     | 1     | 2     | 3     | 4     |
+=======+=======+=======+=======+=======+
| ['t'] | ['i'] | ['t'] | ['l'] | ['e'] |
+-------+-------+-------+-------+-------+
| ['o'] | ['r'] | ['i'] | ['g'] | ['i'] |
+-------+-------+-------+-------+-------+
| ['g'] | ['e'] | ['n'] | ['r'] | ['e'] |
+-------+-------+-------+-------+-------+
| ['v'] | ['o'] | ['t'] | ['e'] | ['_'] |
+-------+-------+-------+-------+-------+
| ['v'] | ['o'] | ['t'] | ['e'] | ['_'] |
+-------+-------+-------+-------+-------+
| ['r'] | ['e'] | ['l'] | ['e'] | ['a'] |
+-------+-------+-------+-------+-------+
| ['p'] | ['o'] | ['p'] | ['u'] | ['l'] |
+-------+-------+-------+-------+-------+
| ['o'] | ['v'] | ['e'] | ['r'] | ['v'] |
+-------+-------+-------+-------+-------+
```

**Comment by bencwallace** [comment]
Kind of unclear what you're trying to do. How is `results` originally defined?

**Comment by AtomicNess123** [comment]
Thanks. To be clear (apologies):

`results=pd.DataFrame(results)`

The results in brackets is a dictionary.
I tried both on the dict and on the resulting dataframe but both give me same weird looking result.
The line of code I use is this:

`results_wrapped = [[textwrap.wrap(cell,w) for w,cell in zip(colwidths, row)] for row in results]`

**Comment by evancamilleri** [comment]
Was there ever a solution to this?

**Comment by astanin** [comment]
@evancamilleri I suppose that this use case is covered by the `maxcolwidths` option. It can be a list of width values.

```pycon
>>> import tabulate as t
>>> print(t.tabulate([["lorem ipsum dolor sit amet"]*3], tablefmt="grid", maxcolwidths=[12, 8]))
+-------------+----------+----------------------------+
| lorem ipsum | lorem    | lorem ipsum dolor sit amet |
| dolor sit   | ipsum    |                            |
| amet        | dolor    |                            |
|             | sit amet |                            |
+-------------+----------+----------------------------+
```

The last common is not wrapped.

**Comment by Asthestarsfalll** [comment]
@astanin Hi, If there is a nested table, the maxcolwidths will cause the inner table abnormal. How can I solve this?
![2024-01-30_21-07](https://github.com/astanin/python-tabulate/assets/72954905/aaa76601-acbb-4070-a3b8-c7b4b2acb36c)
